# 关闭模板引擎缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssmbuild?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.lin.pojo
  mapper-locations:
    - classpath:mybatis/mapper/*.xml