# 关闭模板引擎的缓存
spring:
  thymeleaf:
    cache: false
  # 我们的国际化文件配置文件位置
  messages:
    basename: i18n.login
  mvc:
    format:
      # 修改默认日期格式
      date: yyyy-MM-dd
#配置项目路径
#  mvc:
#    servlet:
#      path: /lin